### ISSUE TITLE
The first verse of all surahs is wrong (Arabic text)

### ISSUE THREAD

**Issue by moazzamk** [GlobalQuran/site#1]
All the views (tajweed, uthmani, etc) start the first verse of with bismillah then have the correct first verse . Both bismilah and the first verse of the surah are joined so people who don't know may think that is the whole verse. Bismillah needs to be removed from the beginning of all surah texts

**Comment by imran20487** [comment]
Is this issue solved?

**Comment by iBasit** [comment]
if someone can provide PR for this request on data repo - https://github.com/GlobalQuran/data

it will automatically be changed on all the websites if pushed to data.

**Comment by iBasit** [comment]
resolved
