### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by olfolf** [GlobalQuran/site#14]
hello
how to test quran with wamp??
i wanna test quran offline.how can i?

**Comment by iBasit** [comment]
You don't need server to test Quran.

Just download and open index.html on browser. it will start showing
directly from the server.


Best Regards
Basit

Live Your Life with Inspiration
http://Basit.me

**Comment by olfolf** [comment]
Hi
We have files word-byword.js and all.js
I want another files such as uthmani.js,  simple.js, etc.
How can i get that files?

**Comment by olfolf** [comment]
Excuse me
Another question

when i open page in browser in offline
the page start to load whole 604 pages.
i.e page start 1 until 604 and page moving up and down.
How can i stop this when i load page in browser?

**Comment by iBasit** [comment]
You can use our download area to download more files http://globalquran.com/download

I'm not sure how to reproduce the the last error you are getting.

**Comment by olfolf** [comment]
Hi
I'm sorry
but i can not download files
because volume file is 20 bytes.
and i have this error.you can download photo then see the error.
This is link download:
http://s6.picofile.com/file/8187021400/Capture.PNG

**Comment by olfolf** [comment]
Please help me
Can you download uthmani.js abd simple.js for me and send to my email?

**Comment by iBasit** [comment]
I have click on small cloud icon to get following url, which you can
download directly

http://api.globalquran.com/complete/quran-simple

http://api.globalquran.com/complete/quran-uthmani-min

**Comment by olfolf** [comment]
Thanks.
But i want JS files uthmani and simple not TXT

**Comment by iBasit** [comment]
Please check our docs

http://docs.globalquran.com/API:Data/Complete_Quran

http://api.globalquran.com/complete/quran-simple?key=api_key&format=json
 (this is json format, which is used for js)

**Comment by olfolf** [comment]
Hello again
This is a link for offline Quran:
http://s000.tinyupload.com/?file_id=39383900854705927299

When i run that in Wamp server page go up and down.
Can you test in your Wamp server and solve for me?

Please test and help me.
I need that.

Thanks.

**Comment by olfolf** [comment]
Please help

**Comment by iBasit** [comment]
Sorry for late response, do you still need help in this?
