### ISSUE TITLE
Email not responding, site not loading and downloads not working

### ISSUE THREAD

**Issue by ATouhou** [GlobalQuran/site#18]
salama aleykoum wa rahmatullahi wa barakatuh. 

the email:      info@globalquran.com is not working.
Download page was not working and entire server (and site) is sometimes more buggy than other times.

**Comment by iBasit** [comment]
wa salaamu waliakum wr wb

Can you share with us what reply do you get on info@globalquran.com? because it works fine from my email.

Yes download is not working, which other place is not working? can you share errors please in detail

**Comment by ATouhou** [comment]
After a few attempts and a few warnings it fails in a complete error.
I will have a look at what other parts was not working,  when I am back on
my computer in Sha Allah

This is an automatically generated Delivery Status Notification

THIS IS A WARNING MESSAGE ONLY.

YOU DO NOT NEED TO RESEND YOUR MESSAGE.

Delivery to the following recipient has been delayed:

     info@globalquran.com

Message will be retried for 2 more day(s)

Technical details of temporary failure:
The recipient server did not accept our requests to connect. Learn more at
https://support.google.com/mail/answer/7720
[(0) dc-73a68650.globalquran.com. [107.191.40.244]:25: socket error]

----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20120113;
        h=mime-version:date:message-id:subject:from:to:content-type;
        bh=pgqlekeVs6sAwW7bfdgEwokEsjSnhMcMjtmw161X5U4=;
        b=mb4oBnkSqIY0j4+t+8hqUZJrbpmaiY6Zoq3seB73/Rq/NdGNIFMNJxrVLXvemQh3zH

 SXH3+WtKSAswW5fUXo2Cf/C4/kDMbs1cqxobOdt497vr/Nubt4MtlQtIl9KqXNByYa5X

 TCqbo2xaCMeQeAXfny3vz9NrO7w9uKvZyldpIbXa/ibJDErit6QcncbBmLMi57HlVAWQ

 Cg6+PqaaoaWe+rVqsa1cBqHGQu8HAcpizZ1kpztflpjEjqR+FKdVHx9C9fWGq7omvtL8

 tS8UcVNIVqF4T4ziy030OYqV99agpcn2y9gaqLtNeFbT/6lR9a47QooimWerLy59l3ZT
         TbKw==
MIME-Version: 1.0
X-Received: by 10.180.24.65 with SMTP id s1mr6619332wif.66.1435760452488;
Wed,
 01 Jul 2015 07:20:52 -0700 (PDT)
Received: by 10.28.177.68 with HTTP; Wed, 1 Jul 2015 07:20:52 -0700 (PDT)
Date: Wed, 1 Jul 2015 16:20:52 +0200
Message-ID: <CAGB+5YFX=E2hcCPuTf2tv7Wh5FK-C_0jhM=
27stx9AcSSy8Hcw@mail.gmail.com>
Subject: Download page is broken
From: Adam Touhou <adatouh@gmail.com>
To: info@globalquran.com
Content-Type: multipart/alternative; boundary=f46d043bdf2ac0d4430519d1078b
Den 09/07/2015 22.05 skrev "Basit" <notifications@github.com>:

**Comment by iBasit** [comment]
Email is getting sorted out, after 48 hours it will be fixed. I hope sooner. 

Download page if fixed and I'm not sure about what other bugs, but if you find any please put it here. 

Jazak'Allah khair
