### ISSUE TITLE
Download: Surah by surah 114 files json format is not available for download

### ISSUE THREAD

**Issue by imran20487** [GlobalQuran/site#19]
The page says the following are available for download but there is no option to download:
Multiple Files of Surah, Page and Juz
Surah by Surah
Surah by surah is distributed into 114 surah files in json format.

Page by Page
Page by page is distributed into 604 files in json format.

Juz by Juz
Juz by juz is distributed into 30 juz files in json format.

**Comment by iBasit** [comment]
Sorry for very late response. But does this is still in issue?

**Comment by imran20487** [comment]
yes, When I select the Download button, it has only options for text, json and js. there is no option for By Surah/By Juz/By page.
