### ISSUE TITLE
Quran-kids json: What is the significance of some random numbers in the json like this |154|191|48$

### ISSUE THREAD

**Issue by imran20487** [GlobalQuran/site#20]
For example:
|In (the) name|112|146|1$
|All praises and thanks|164|194|5$
|(the) Lord|87|148|7$

I don't understand what those numbers indicate?

**Comment by iBasit** [comment]
Sorry for late reply, please ignore the numbers

**Comment by imran20487** [comment]
It is difficult to parse (ignore) those numbers when displaying. It would be better if it weren't there in teh json file at all.
Jazakallahu Khair.

**Comment by iBasit** [comment]
We have functions for that, if you still need it, I can share it with you. its on our GQ.js file. 

We can't remove it anymore, because lots of people are using our api and just to make any update or specially remove, it might endup breaking others system / applications.

**Comment by imran20487** [comment]
Yes please. You can send me the GQ.js file to imran.ar20487@gmail.com

**Comment by iBasit** [comment]
https://github.com/GlobalQuran/site/blob/master/upload/js/gq.js
