### ISSUE TITLE
"double consonants" are missing from some Surah

### ISSUE THREAD

**Issue by noman650** [GlobalQuran/site#23]
AOA

Please find attached screenshot which will show you about missing "double consonants" these words are important as they help us to ready Quran Correctly. I recently noticed and realized i was reading wrong, pls correct this ASAP. 

Waiting for your reply soon.

![missing words](https://cloud.githubusercontent.com/assets/16926458/12627670/f45555da-c560-11e5-8cc8-6f8e4801ba2a.png)
JazakAllah

**Comment by ashraf-ali-ca** [comment]
@noman650 Walaikum salam, Brother this issue might be due to arabic font not render correctly on browser but you could use http://www.recitequran.com/ as they use images, also if you have a android device you can use https://play.google.com/store/apps/details?id=ir.sabapp.AmmaJoz&hl=en_GB which has word for word audio, Inshallah am hoping to implement word for word audio into global quran.

**Comment by iBasit** [comment]
@noman650 brother have you tried changing to different fonts?

**Comment by noman650** [comment]
Thanks Ashraf, but i think these missing letters will change the meaning for a person who dont understand arabic so it should be fixed ASAP or make a note on site to sue other site for reading.

**Comment by noman650** [comment]
Salam Basit, I am not sure how to change font, i am using google chrome browser

**Comment by iBasit** [comment]
wa salaam.

Insha'Allah if Allah wills, we will have completely new design this year.  

changing font!!!, even I got confused where it was lol.

On top of Quran list there is a setting link, please click on it. 
![image](https://cloud.githubusercontent.com/assets/34341/12704993/42e84486-c85f-11e5-9f1f-ebff07336d71.png)

**Comment by noman650** [comment]
OK, i am on this site: v2.globalquran.com/73 
but cannot see the settings
Am i on correct site?

**Comment by noman650** [comment]
Ok i found it here: http://globalquran.com/quran-uthmani/73:1
and settings are already set there but still without "double consonants"

Also same on this site: http://www.recitequran.com/73:1
will check reply tomorrow.

**Comment by iBasit** [comment]
Are you using mac?

**Comment by noman650** [comment]
I am using Windows 7, DO you see this issue on your PC?

**Comment by iBasit** [comment]
As salaamu walikum wr wb

http://www.abouttajweed.com/kb/entry/594/

The reason there is no shaddah written on the  and    when the  saakinah or tanween merge into them, is that the idhgaam is incomplete ( ) in that the ghunnah of the noon remains.  For that reason most copies of the Qur'an do not have the extra marking of a shaddah.  
Please note, the shaddah is not part of the 'Uthmani writing but part of the enhancements done later in time by scholars to aid in the correct reading of the Qur'an.  
Please see: http://www.abouttajweed.com/the-noon-saakinah-and-tanween/merging-of-the-noon-saakinah-and-tanween-p.html
