### ISSUE TITLE
Quran corpus text not readable

### ISSUE THREAD

**Issue by woobingcn** [GlobalQuran/site#25]
Corpus text not readable at site  
http://globalquran.com/quran-corpus-qd+quran-wordbyword/1  
can someone fix it or have idea why?

it works well at site
http://labs.globalquran.com/corpus/#!/quran-corpus/1

**Comment by iBasit** [comment]
It is not suppose to show on GQ old site, we will implement this on new version #v5. will filter it out insha'Allah.
