### ISSUE TITLE
http://globalquran.com/ and api down

### ISSUE THREAD

**Issue by mjunaidsalaat** [GlobalQuran/site#26]
AsSalaam U Alikum.

http://globalquran.com/ website is continuously loading and Quran API is also not responding correctly.

for example i'm hitting.
`http://api.globalquran.com/complete/ur.kanzuliman`

and I'm getting 200 status and this response.
`<br />
<b>Fatal error</b>:  Call to a member function query() on null in <b>/home/gq/wLib/include/_lib/Database.class.php</b> on line <b>580</b><br />
`

And BTW Great Effort (Y) in building this and the new Quran app..

Thanks.

**Comment by iBasit** [comment]
Wa salaamu waliakum wr wb

Sorry for inconvenience, It is up and running again.
