### ISSUE TITLE
Times are forwarded by 1 hour through api call

### ISSUE THREAD

**Issue by fahim0173** [GlobalQuran/site#27]
Hi, 

We are using MuslimSalat for retrieving Wakt times for different zones of Bangladesh. The times seem to be forwarded by 1 hour. This is also replicated in the website. If you go in first it has right times, but if you change tabs and come back, it forwards time by 1 hr.

We hope this can be resolved quickly.

Thank you.
Fahim

**Comment by iBasit** [comment]
Salaam,

There is daylight parameter, you have to set the value to false, as no daylight saving, that will give you 1 hour less.
