### ISSUE TITLE
ISSUE WITH GLOBAL QURAN

### ISSUE THREAD

**Issue by allinitsolutions** [GlobalQuran/site#28]
Hi

We have this wordpress plugin on our web site and every now and again we have the attached issue.

Then we go to your site and it seems to be the same? Does you server go down? If so we have our own dedicated servers which i'm happy to host this on. 

Please advise, i believe something as beneficial as this should not compromise in service to the greater community.

Please advise.
![screen shot 2016-06-20 at 7 04 28 am](https://cloud.githubusercontent.com/assets/20031913/16179843/80422602-36b5-11e6-9349-8b2339e25c55.png)

**Comment by iBasit** [comment]
Issue is resolved.
