### ISSUE TITLE
Issue in namaz timing api

### ISSUE THREAD

**Issue by awais4code** [GlobalQuran/site#29]
Namaz timing api oftenly shows this error: 
Could not connect to the database 2002 - DB Error.

**Comment by awais4code** [comment]
<img width="472" alt="screen shot 2016-06-20 at 2 36 52 pm" src="https://cloud.githubusercontent.com/assets/20041431/16189683/126b4cf4-36f5-11e6-81b3-a9d1c3d75fc8.png">

**Comment by iBasit** [comment]
It should not be showing anymore, please remove cache and try again

**Comment by awais4code** [comment]
I am using this api in a mobile app, mobile app crashes when this type of thing occurs

**Comment by iBasit** [comment]
What is the mobile app name?

Hopefully you won't face this issue on 2.0. - We are getting lots of hits from different apps and sites in Ramadan.

**Comment by awais4code** [comment]
App Name: sehr o iftaar Reminders

 When you are going to release 2.0?

**Comment by iBasit** [comment]
it won't be anytime soon, most likely in 4+ months insha'Allah.

**Comment by awais4code** [comment]
insha'Allah. Best of luck

**Comment by iBasit** [comment]
jazak'Allah khair
