### ISSUE TITLE
GlobalQuran API is down with an error 

### ISSUE THREAD

**Issue by Inshra-1327-f10B** [GlobalQuran/site#30]
<b>Fatal error</b>:  Call to a member function query() on null in <b>/home/gq/wLib/include/_lib/Database
.class.php</b> on line <b>580</b><br />

**Comment by iBasit** [comment]
Has been fixed. Sorry for inconvenience.


Best Regards
Basit

**Comment by Inshra-1327-f10B** [comment]
thank you so much for the fix and a quick response
