### ISSUE TITLE
Error on signup on website https://globalquran.com/contribute/signup_form.php

### ISSUE THREAD

**Issue by AshfaqAliZardariOfficial** [GlobalQuran/site#53]
# Unable to signup on the website: https://globalquran.com/contribute/signup_form.php

## Error Shows:

<html>
<body>

[1062] : Duplicate entry '915' for key 'PRIMARY'
--
[cencord]
Database->Save ( 'boolean, ' ) | 434 | [i]..._lib/Model.class.php
Model->save ( ) | 707 | [i]..._lib/Login.class.php
Login->save ( ) | 28 | [i]...odule/user.class.php
user->save ( ) | 85 | [i]...bute/signup_form.php
user->save ( ) | 85 | [i]...

</body>
</html>

**Comment by iBasit** [comment]
As Salaamu wa alaikum,

The issue has been resolved.

**Comment by AshfaqAliZardariOfficial** [comment]
Ok let me check it.

**Comment by AshfaqAliZardariOfficial** [comment]
Thank you very much! It's working now.
